version: '3.8'

services:
  web:
    build: 
      context: .
      target: debug
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - .:/usr/src/app
    command: go run main.go -b 0.0.0.0
    security_opt:
      - "seccomp:unconfined"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: always
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  postgres-db: