
SELECT *
FROM pg_stat_activity
WHERE datname = 'motel';

SELECT
	pg_terminate_backend (pg_stat_activity.pid)
FROM
	pg_stat_activity
WHERE
	pg_stat_activity.datname = 'motel';

drop database motel;

create database motel;

-- create table flows
drop table flows
CREATE TABLE flows(
	flow_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	flow_name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO flows (flow_name) VALUES
	('flow-A'),
	('flow-B'),
	('flow-C'),
	('flow-D'),
	('flow-E'),
	('flow-F'),
	('flow-G'),
	('flow-H'),
	('flow-K'),
	('flow-KIOT');
SELECT * FROM flows;

-- create table room
CREATE TABLE room(
	room_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	flow_id INT NULL REFERENCES flows(flow_id),
	room_name VARCHAR(255) NOT NULL UNIQUE,
	booking_date TIMESTAMP,
	date_move_in TIMESTAMP,
	electric_number INT,
	deposits FLOAT,
	img_electric TEXT,
	img_room_rates TEXT,
	img_water FLOAT,
	junk_money FLOAT,
	num_of_member INT,
	room_rates FLOAT,
	water_number FLOAT
);

INSERT INTO room(
	flow_id, room_name,booking_date,date_move_in,electric_number,
	deposits,img_electric,img_room_rates,img_water,junk_money,
	num_of_member,room_rates,water_number) VALUES 
	(1,'A1',now(),now(),0,0,'','',0,0,0,0,0),
	(1,'A2',now(),now(),0,0,'','',0,0,0,0,0),
	(2,'B2',now(),now(),0,0,'','',0,0,0,0,0),
	(2,'B3',now(),now(),0,0,'','',0,0,0,0,0),
	(3,'C1',now(),now(),0,0,'','',0,0,0,0,0),
	(4,'D1',now(),now(),0,0,'','',0,0,0,0,0),
	(5,'E1',now(),now(),0,0,'','',0,0,0,0,0);

SELECT * FROM room;

-- create table roles
CREATE TABLE roles(
	role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	role_name VARCHAR(50) NOT NULL UNIQUE,
	grant_date TIMESTAMP
);

INSERT INTO roles(role_name, grant_date) VALUES
	('admin',NOW()),
	('host',NOW()),
	('manager',NOW()),
	('client',NOW()),
	('user',NOW());
	
SELECT * FROM roles;

-- create table accountss
CREATE TABLE accounts(
	user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	room_id INT NULL REFERENCES room (room_id),
	user_name VARCHAR(512) UNIQUE NOT NULL,
	password VARCHAR(1024) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL,
    last_login TIMESTAMP NOT NULL
);

INSERT INTO accounts(
	room_id, user_name,password,email,created_on,last_login) VALUES
	(NULL,'admin','admin','admin@gmail.com',NOW(),NOW()),
	(1,'A1-034982142','123456789','abc1@gmail.com',NOW(),NOW()),
	(2,'B1-034982142','123456789','abc2@gmail.com',NOW(),NOW()),
	(3,'C1-034982142','123456789','abc3@gmail.com',NOW(),NOW()),
	(4,'D1-034982142','123456789','abc4@gmail.com',NOW(),NOW()),
	(5,'E1-034982142','123456789','abc5@gmail.com',NOW(),NOW()),
	(5,'K1-034982142','123456789','abc6@gmail.com',NOW(),NOW()),
	(5,'G1-034982142','123456789','abc7@gmail.com',NOW(),NOW()),
	(5,'H1-034982142','123456789','abc8@gmail.com',NOW(),NOW()),
	(5,'KIOT1-034982142','123456789','abc9@gmail.com',NOW(),NOW()),
	(5,'F1-034982142','123456789','abc10@gmail.com',NOW(),NOW());

SELECT * FROM accounts;
