
SELECT *
FROM pg_stat_activity
WHERE datname = 'motel';

SELECT
	pg_terminate_backend (pg_stat_activity.pid)
FROM
	pg_stat_activity
WHERE
	pg_stat_activity.datname = 'motel';

drop database motel;

create database motel;

-- create table---------------------------------------------------------------------------------------------------
drop table flows;
drop TABLE accounts;
drop TABLE rooms;
drop TABLE roles;

CREATE TABLE flows(
	flow_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	flow_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE roles(
	role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	role_name VARCHAR(50) NOT NULL UNIQUE,
	grant_date TIMESTAMP
);

CREATE TABLE rooms(
	room_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	flow_id INT NULL REFERENCES flows(flow_id),
	status_room INT NOT NULL,
	room_name VARCHAR(255) NOT NULL UNIQUE,
	booking_date TIMESTAMP NULL,
	date_move_in TIMESTAMP NULL,
	date_move_out TIMESTAMP NULL,
	total_days FLOAT,
	electric_number FLOAT,
	electric_price FLOAT,
	deposits FLOAT,
	img_electric TEXT,
	img_room_rates TEXT,
	img_water TEXT,
	junk_money FLOAT,
	num_of_member INT,
	room_rates FLOAT,
	water_number FLOAT,
	water_price FLOAT
);

CREATE TABLE accounts(
	account_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	room_id INT NULL REFERENCES room (room_id),
	user_name VARCHAR(512) UNIQUE NOT NULL,
	password VARCHAR(1024) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL,
    last_login TIMESTAMP NOT NULL
);


-- SELECT TABLE ------------------------------------------------------------------------------------------------------------
SELECT * FROM rooms;
SELECT * FROM flows;
SELECT * FROM roles;
SELECT * FROM accounts;


-- INSERT TABLE----------------------------------------------------------------------------------------------------------
INSERT INTO flows (flow_name) VALUES
	('flow-A'),
	('flow-B'),
	('flow-C'),
	('flow-D'),
	('flow-E'),
	('flow-F'),
	('flow-G'),
	('flow-H'),
	('flow-K'),
	('flow-KIOT');

INSERT INTO roles(role_name, grant_date) VALUES
	('admin',NOW()),
	('host',NOW()),
	('manager',NOW()),
	('client',NOW()),
	('user',NOW());

INSERT INTO rooms(
	flow_id,status_room, room_name, booking_date,date_move_in,
	date_move_out,total_days,electric_number,electric_price,
	deposits,img_electric,img_room_rates,img_water,junk_money,
	num_of_member,room_rates,water_number,water_price) VALUES
	-- A --
	(1,0,'A1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	(1,0,'A2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(1,0,'A10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	-- B --
	(2,0,'B1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(2,0,'B10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	-- C --
	(3,0,'C1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(3,0,'C10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	-- D --
	(4,0,'D0',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	(4,0,'D1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(4,0,'D10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	-- E --
	(5,0,'E0',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(5,0,'E10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	-- F --
	(6,0,'F1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1000000,0,10000),
	(6,0,'F2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(6,0,'F10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1000000,0,10000),
	-- G --
	(7,0,'G1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(7,0,'G11',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1200000,0,10000),
	-- H --
	(8,0,'H0',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	(8,0,'H1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(8,0,'H11',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1200000,0,10000),
	-- K --
	(9,0,'K0',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,900000,0,10000),
	(9,0,'K1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K6',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K7',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K8',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K9',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K10',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	(9,0,'K11',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,800000,0,10000),
	-- KIOT --
	(10,0,'KIOT1',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,3000000,0,10000),
	(10,0,'KIOT2',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1400000,0,10000),
	(10,0,'KIOT3',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,1600000,0,10000),
	(10,0,'KIOT4',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,2000000,0,10000),
	(10,0,'KIOT5',NULL,NULL,NULL,0,0,3000,0,'','','',15000,0,2000000,0,10000);



INSERT INTO accounts(
	room_id, user_name,password,email,created_on,last_login) VALUES
	(NULL,'admin','admin','admin@gmail.com',NOW(),NOW()),
	(1,'A1-034982142','123456789','abc1@gmail.com',NOW(),NOW()),
	(1,'A10-034982142','123456789','abc12@gmail.com',NOW(),NOW()),
	(2,'B1-034982142','123456789','abc2@gmail.com',NOW(),NOW()),
	(3,'C1-034982142','123456789','abc3@gmail.com',NOW(),NOW()),
	(4,'D1-034982142','123456789','abc4@gmail.com',NOW(),NOW()),
	(5,'E1-034982142','123456789','abc5@gmail.com',NOW(),NOW()),
	(6,'F1-034982142','123456789','abc6@gmail.com',NOW(),NOW()),
	(7,'G1-034982142','123456789','abc7@gmail.com',NOW(),NOW()),
	(8,'H1-034982142','123456789','abc8@gmail.com',NOW(),NOW()),
	(9,'K1-034982142','123456789','abc10@gmail.com',NOW(),NOW()),
	(10,'KIOT1-034982142','123456789','abc13@gmail.com',NOW(),NOW()),
	(10,'KIOT2-034982142','123456789','abc11@gmail.com',NOW(),NOW());
	
SELECT *From rooms;
