DROP TABLE IF EXISTS flow CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS bill CASCADE;
DROP TABLE IF EXISTS role_account CASCADE;